require('config.autoread')
require('config.globals')
require('config.options')
require('config.keymaps')
require('config.filetypes')
require('config.diagnostics')
require('config.gui')
require('config.lazy')
